#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)
manifest="$repo_root/tests/unreal/p1.4-manifest.json"; p13_manifest="$repo_root/tests/unreal/p1.3-manifest.json"
engine_root=$(cd "${UE_ENGINE_ROOT:-/Users/Shared/Epic Games/UE_5.8}" && pwd -P)
run_uat="$engine_root/Engine/Build/BatchFiles/RunUAT.sh"; editor_cmd="$engine_root/Engine/Binaries/Mac/UnrealEditor-Cmd"; dotnet_root="$engine_root/Engine/Binaries/ThirdParty/DotNet/10.0/mac-arm64"; version_file="$engine_root/Engine/Binaries/Mac/UnrealEditor.version"
[[ -f "$manifest" && -f "$p13_manifest" && -x "$run_uat" && -x "$editor_cmd" && -x "$dotnet_root/dotnet" ]]
operations=(ai.controller_configure ai.pawn_configure behavior_tree.connect behavior_tree.create behavior_tree.node_ensure behavior_tree.view blackboard.create blackboard.key_ensure blackboard.view navigation.build navigation.status navigation.bounds_ensure navigation.path_query play.ai_target_set play.ai_observe)
ops_json=$(printf '%s\n' "${operations[@]}" | jq -Rsc 'split("\n")[:-1]')
jq -e --argjson ops "$ops_json" --slurpfile p13 "$p13_manifest" '
 .phase=="P1.4" and .engine=={version:"5.8.1",changelist:56057345,hostArchitecture:"arm64"} and .catalog=={count:70,sha256:"6161e017548d1e576b9bb8ecf42f75c69519b9d38e128c86c83611ff4fdd89de"} and
 (.nativeTests|length)==6 and (.nativeTests|unique|length)==6 and (.p13RegressionTests|length)==27 and (.automationTests|length)==33 and (.automationTests|unique|length)==33 and .p13RegressionTests==$p13[0].automationTests and ((.p13RegressionTests+.nativeTests)|sort)==(.automationTests|sort) and
 .fixture.arrivalDistanceTolerance==50 and .fixture.arrivalTimeoutSeconds==120 and (.liveAssertions|index("deterministic-second-session-reset"))!=null and .pipeline=={blueprintOnly:true,compileAllBlueprints:true,cook:true,package:true} and .plugin.binary=="libUnrealEditor-MagiUnrealAXI.dylib" and .plugin.requiredArchitectures==["arm64","x86_64"] and (.plugin.sourceRoot|type)=="string" and (.cli.binary|type)=="string" and
 ([.packageAssertions.blackboard,.packageAssertions.behaviorTree,.packageAssertions.controller,.packageAssertions.pawn,.packageAssertions.floor]|all(.file|type=="string" and startswith("MagiP14/"))) and (.packageAssertions.map|type)=="string" and (.packageAssertions.map|startswith("MagiP14/")) and
 (([.packageAssertions.blackboard,.packageAssertions.behaviorTree,.packageAssertions.controller,.packageAssertions.pawn,.packageAssertions.floor]|map(.object)) as $objects | ($objects|all(type=="string" and startswith("/Game/MagiP14/"))) and ($objects|unique|length==5)) and ([.packageAssertions.controller,.packageAssertions.pawn,.packageAssertions.floor]|all(.generatedRuntime|type=="string" and endswith("_C"))) and (.packageAssertions.mapPackage|startswith("/Game/MagiP14/")) and
 (.operationCertificationCells|length)==15 and ([.operationCertificationCells[].operation]|sort)==($ops|sort) and ([.operationCertificationCells[].operation]|unique|length)==15
' "$manifest" >/dev/null
jq -e --arg cell '5.8.1-macos-arm64-56057345' --argjson ops "$ops_json" '[.[]|select(.id as $id | $ops|index($id))|select(.engineSupport.certified==[$cell])]|length==15' "$repo_root/capabilities/catalog.json" >/dev/null
[[ $(uname -m) == arm64 && $(plutil -extract Changelist raw -o - "$version_file") == 56057345 && "$(plutil -extract MajorVersion raw -o - "$version_file").$(plutil -extract MinorVersion raw -o - "$version_file").$(plutil -extract PatchVersion raw -o - "$version_file")" == 5.8.1 ]]

cache_root="$HOME/Library/Caches/magi-unreal-axi/p1.4/native"; mkdir -p "$cache_root"; work=$(mktemp -d "$cache_root/work.XXXXXX"); evidence=$(mktemp -d "$cache_root/evidence.XXXXXX")
cleanup(){ local s=$?; trap - EXIT; if [[ $s != 0 ]]; then echo "P1.4 certification failed; work=$work evidence=$evidence" >&2; for f in "$work"/*.log "$work"/*.stdout; do [[ -f "$f" ]]&&{ echo "--- $f" >&2; tail -80 "$f" >&2; }; done; exit $s; fi; [[ ${KEEP_P14_WORK:-0} == 1 ]]||/usr/bin/trash "$work" 2>/dev/null||true; }; trap cleanup EXIT
source_inventory(){ local out=$1 root; { for root in Cargo.toml Cargo.lock; do [[ -f "$repo_root/$root" ]]&&printf '%s\n' "$repo_root/$root"; done; for root in src capabilities plugin tests/unreal protocol guidance; do [[ -d "$repo_root/$root" ]]||continue; find "$repo_root/$root" \( -type d \( -name Saved -o -name Binaries -o -name Intermediate -o -name DerivedDataCache \) -prune \) -o -type f -print; done; }|sed "s#^$repo_root/##"|LC_ALL=C sort -u|while IFS= read -r f; do [[ -f "$repo_root/$f" ]]||return 1; printf '%s\t%s\n' "$f" "$(shasum -a 256 "$repo_root/$f"|cut -d' ' -f1)"; done >"$out"; [[ -s "$out" ]]&&LC_ALL=C sort -c "$out"; awk -F '\t' 'NF!=2||$2!~/^[0-9a-f]{64}$/{exit 1}' "$out"; }
inventory_tree(){ local root=$1 out=$2; [[ -z "$(find "$root" ! -type d ! -type f -print -quit)" ]]; (cd "$root"&&find . -type f -print|LC_ALL=C sort|while IFS= read -r f; do printf '%s\t%s\n' "${f#./}" "$(shasum -a 256 "$f"|cut -d' ' -f1)"; done)>"$out"; [[ -s "$out" ]]&&LC_ALL=C sort -c "$out"; }
scan_secrets(){ local root=$1 s; [[ -z "$(find "$root" -type f \( -name token -o -name bridge-v1.json \) -print -quit)" ]]; set +e; grep -R -I -E -q 'Authorization:[[:space:]]*Bearer[[:space:]]+[A-Za-z0-9._-]+' "$root"; s=$?; set -e; [[ $s == 1 ]]; }
mkdir -p "$work/project/Plugins" "$work/plugin" "$work/report" "$work/cooked" "$work/package" "$work/package-inventory" "$work/registry-dump"; source_inventory "$work/source-inventory-before.txt"; source_before=$(shasum -a 256 "$work/source-inventory-before.txt"|cut -d' ' -f1); source_root=$(jq -r .plugin.sourceRoot "$manifest"); inventory_tree "$repo_root/$source_root" "$work/plugin-source-tree-before.txt"; plugin_source=$(shasum -a 256 "$work/plugin-source-tree-before.txt"|cut -d' ' -f1)
package_project_dir="$work/package-project"; mkdir -p "$package_project_dir/Config"; cp "$repo_root/tests/unreal/MagiUnrealAXIPackageFixture/MagiUnrealAXIPackageFixture.uproject" "$package_project_dir/"
cat >"$package_project_dir/Config/DefaultEngine.ini" <<EOF
[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=$(jq -r .fixture.level "$manifest")
EditorStartupMap=$(jq -r .fixture.level "$manifest")
GlobalDefaultGameMode=/Script/Engine.GameModeBase
EOF
cat >"$package_project_dir/Config/DefaultGame.ini" <<EOF
[/Script/UnrealEd.ProjectPackagingSettings]
+MapsToCook=(FilePath="$(jq -r .fixture.level "$manifest")")
+DirectoriesToAlwaysCook=(Path="/Game/$(jq -r .packageAssertions.contentRoot "$manifest")")
UsePakFile=True
bUseIoStore=True
bUseZenStore=False
EOF
for x in Source Modules Plugins Binaries Intermediate Saved DDC DerivedDataCache; do [[ ! -e "$package_project_dir/$x" ]]; done; export DOTNET_ROOT="$dotnet_root" PATH="$dotnet_root:$PATH"
catalog_line=$(cargo run --locked --manifest-path "$repo_root/Cargo.toml" --bin xtask -- capabilities check); printf '%s\n' "$catalog_line">"$work/catalog-check.txt"; catalog_count=$(sed -E 's/^capability catalog: ([0-9]+) records.*/\1/'<<<"$catalog_line"); catalog_hash=$(sed -E 's/.*sha256:([0-9a-f]{64})$/\1/'<<<"$catalog_line"); [[ $catalog_count == 70 && $catalog_hash == "$(jq -r .catalog.sha256 "$manifest")" ]]
cargo test --all-targets --all-features --locked --manifest-path "$repo_root/Cargo.toml">"$work/rust-tests.log" 2>&1; cargo build --release --locked --manifest-path "$repo_root/Cargo.toml">"$work/release-build.log" 2>&1; cargo fmt --manifest-path "$repo_root/Cargo.toml" --all -- --check>"$work/fmt.log" 2>&1; cargo clippy --all-targets --all-features --locked --manifest-path "$repo_root/Cargo.toml" -- -D warnings>"$work/clippy.log" 2>&1
cli="$repo_root/$(jq -r .cli.binary "$manifest")"; [[ -x "$cli" ]]; cli_hash=$(shasum -a 256 "$cli"|cut -d' ' -f1); cp "$cli" "$work/magi-unreal-axi"; chmod 0755 "$work/magi-unreal-axi"; "$run_uat" BuildPlugin -Plugin="$repo_root/plugin/MagiUnrealAXI/MagiUnrealAXI.uplugin" -Package="$work/plugin" -TargetPlatforms=Mac>"$work/plugin-build.log" 2>&1; plugin_binary=$(find "$work/plugin" -type f -name "$(jq -r .plugin.binary "$manifest")" -print -quit); [[ -n "$plugin_binary" ]]; arches=$(lipo -archs "$plugin_binary"); for a in $(jq -r '.plugin.requiredArchitectures[]' "$manifest"); do grep -qw "$a"<<<"$arches"; done; [[ $(wc -w<<<"$arches"|tr -d ' ') == 2 ]]; artifact=$(shasum -a 256 "$plugin_binary"|cut -d' ' -f1)
ditto "$repo_root/tests/unreal/MagiUnrealAXIFixture" "$work/project"; ditto "$work/plugin" "$work/project/Plugins/MagiUnrealAXI"; project="$work/project/MagiUnrealAXIFixture.uproject"; package_project="$package_project_dir/MagiUnrealAXIPackageFixture.uproject"; axi=("$work/magi-unreal-axi" --project "$project" --engine "$engine_root" --timeout 1800 --format json); package_axi=("$work/magi-unreal-axi" --project "$package_project" --engine "$engine_root" --timeout 7200 --format json)
"${axi[@]}" project build>"$work/project-build.json"; jq -e '.operation.kind=="build" and (.operation.status=="passed" or .operation.status=="up_to_date")' "$work/project-build.json">/dev/null; "$editor_cmd" "$project" -run=CompileAllBlueprints -unattended -nop4 -nosplash -nullrhi -NoSound -log="$work/compile.log">"$work/compile.stdout" 2>&1; grep -E '0 error\(s\), 0 warning\(s\)' "$work/compile.stdout">"$work/compile-proof.txt"
"${axi[@]}" project test list --filter MagiUnrealAXI --limit 100 >"$work/test-list.json"; jq -e --slurpfile m "$manifest" '(.count==33 and .total==33 and ([.items[].id]|sort)==($m[0].automationTests|sort))' "$work/test-list.json">/dev/null; "${axi[@]}" project test run --filter MagiUnrealAXI --report "$work/report">"$work/test-run.json"; jq -e '.totals.failed==0 and .totals.notRun==0 and .totals.inProcess==0 and .totals.matched==33' "$work/test-run.json">/dev/null; jq -e --slurpfile m "$manifest" '(.tests|map(.fullTestPath)|sort)==($m[0].automationTests|sort) and all(.tests[];.state=="Success" and .errors==0)' "$work/report/index.json">/dev/null
live="$work/live-evidence"; P14_LIVE_EVIDENCE_DIR="$live" P14_PACKAGE_PROJECT_DIR="$package_project_dir" P14_CLI_PATH="$work/magi-unreal-axi" P14_CLI_SHA256="$cli_hash" P14_PLUGIN_DIR="$work/plugin" P14_PLUGIN_SHA256="$artifact" P14_WORKSPACE="$work" "$repo_root/tests/unreal/certify-p1.4-live.sh">"$work/live-certification.log" 2>&1; [[ -d "$live" ]]; grep -qx 'phase=P1.4' "$live/summary.txt"; grep -qx "catalogHash=$catalog_hash" "$live/summary.txt"; grep -qx "artifactSha256=$artifact" "$live/summary.txt"; grep -qx "cliSha256=$cli_hash" "$live/summary.txt"; grep -qx 'tokenScan=passed' "$live/summary.txt"
keys=(blackboard behaviorTree controller pawn floor); for k in "${keys[@]}"; do f=$(jq -r ".packageAssertions.$k.file" "$manifest"); [[ -f "$package_project_dir/Content/$f" ]]; done; map_file=$(jq -r .packageAssertions.map "$manifest"); [[ -f "$package_project_dir/Content/$map_file" ]]; "$editor_cmd" "$package_project" -run=CompileAllBlueprints -unattended -nop4 -nosplash -nullrhi -NoSound -log="$work/package-compile.log">"$work/package-compile.stdout" 2>&1; grep -E '0 error\(s\), 0 warning\(s\)' "$work/package-compile.stdout">"$work/package-compile-proof.txt"
"${package_axi[@]}" project cook --output "$work/cooked">"$work/cook.json"; "${package_axi[@]}" project package --output "$work/package">"$work/package.json"; jq -e '.operation.status=="passed" and (.artifacts|length)>0' "$work/cook.json" "$work/package.json">/dev/null; for j in "$work/cook.json" "$work/package.json"; do id=$(jq -r .operation.id "$j"); "${package_axi[@]}" operation view "$id">"$work/operation-$id.json"; jq -e --arg id "$id" '.operation.id==$id and .operation.status=="passed"' "$work/operation-$id.json">/dev/null; done
find "$work/package" -type d -name '*.app' -print -quit|grep -q .; utoc=$(find "$work/package" -type f -name 'MagiUnrealAXIPackageFixture-Mac.utoc' -print -quit); [[ -n "$utoc" ]]; unreal_pak="$engine_root/Engine/Binaries/Mac/UnrealPak"; [[ -x "$unreal_pak" ]]; "$unreal_pak" -ListContainer="$utoc" -Csv="$work/package-inventory/iostore.csv">"$work/package-inventory/unrealpak.log" 2>&1
assert_export(){ awk -F',' -v e="/Content/$1" 'NR>1{f=$5;c=$12;gsub(/^[[:space:]]+|[[:space:]]+$/, "",f);gsub(/^[[:space:]]+|[[:space:]]+$/, "",c);if(substr(f,length(f)-length(e)+1)==e&&c=="ExportBundleData")ok=1}END{exit !ok}' "$work/package-inventory/iostore.csv"; }; for k in "${keys[@]}"; do assert_export "$(jq -r ".packageAssertions.$k.file" "$manifest")"; done; assert_export "$map_file"
registry=$(find "$work/cooked" -type f -name AssetRegistry.bin -print -quit); [[ -n "$registry" ]]; "$editor_cmd" "$package_project" -run=AssetRegistryDump "-input=$registry" "-outdir=$work/registry-dump" -unattended -nop4 -nosplash -nullrhi -NoSound>"$work/registry-dump.log" 2>&1; registry_utf8="$work/registry-dump-utf8.txt"; :>"$registry_utf8"; while IFS= read -r f; do bom=$(od -An -tx1 -N2 "$f"|tr -d '[:space:]'); [[ $bom == fffe || $bom == feff ]]&&iconv -f UTF-16 -t UTF-8 "$f">>"$registry_utf8"||cat "$f">>"$registry_utf8"; printf '\n'>>"$registry_utf8"; done < <(find "$work/registry-dump" -type f -not -name '*.log' -print|LC_ALL=C sort); [[ -s "$registry_utf8" ]]; registry_text="$work/registry-dump-normalized-utf8.txt"; LC_ALL=C tr '[:upper:]' '[:lower:]'<"$registry_utf8">"$registry_text"
group(){ awk -v s="$1" -v e="$2" '$0=="--- begin "s" ---"{i=1;next}i&&/^--- end /{exit f?0:1}i{gsub(/^[[:space:]]+|[[:space:]]+$/, "");if($0==e)f=1}END{exit f?0:1}' "$registry_text"; }; prop(){ awk -v p="$1" -v e="$2" '{l=$0;gsub(/^[[:space:]]+/,"",l)}l~"^"p" :"{i=1;next}i&&l~/^[^[:space:]]/&&l~/ :/{exit f?0:1}i{gsub(/[[:space:]]+$/, "",l);if(l==e)f=1}END{exit f?0:1}' "$registry_text"; }
for k in "${keys[@]}"; do o=$(jq -r ".packageAssertions.$k.object" "$manifest"|tr '[:upper:]' '[:lower:]'); group cachedassetsbyobjectpath "$o"; done; for k in controller pawn floor; do o=$(jq -r ".packageAssertions.$k.object" "$manifest"|tr '[:upper:]' '[:lower:]'); p=${o%.*}; g=$(jq -r ".packageAssertions.$k.generatedRuntime" "$manifest"|tr '[:upper:]' '[:lower:]'); prop generatedclass "$o, /script/engine.blueprintgeneratedclass'$p.$g'"; done; mp=$(jq -r .packageAssertions.mapPackage "$manifest"|tr '[:upper:]' '[:lower:]'); prop /script/engine.world "$mp.$(basename "$mp")"
inventory_tree "$work/cooked" "$work/package-inventory/cooked-tree.txt"; inventory_tree "$work/package" "$work/package-inventory/package-tree.txt"; set +e; grep -R -I -E -q '/Script/(MagiUnrealAXIFixture|MagiUnrealAXI)' "$registry_text" "$work/package-inventory"; forbidden=$?; set -e; [[ $forbidden == 1 ]]; printf 'forbiddenReferences=%s\n' "$forbidden">"$work/forbidden-reference-status.txt"
source_inventory "$work/source-inventory-after.txt"; source_after=$(shasum -a 256 "$work/source-inventory-after.txt"|cut -d' ' -f1); diff -u "$work/source-inventory-before.txt" "$work/source-inventory-after.txt">"$work/source-inventory.diff"; [[ ! -s "$work/source-inventory.diff" && $source_before == "$source_after" ]]
ditto "$live" "$evidence/live"; cp "$manifest" "$evidence/manifest.json"; cp "$work"/{catalog-check.txt,compile-proof.txt,package-compile-proof.txt,source-inventory-before.txt,source-inventory-after.txt,source-inventory.diff,plugin-source-tree-before.txt,forbidden-reference-status.txt,registry-dump-utf8.txt,registry-dump-normalized-utf8.txt} "$evidence/"; cp "$work"/*.log "$work"/*.stdout "$work"/*.json "$evidence/" 2>/dev/null||true; ditto "$work/package-inventory" "$evidence/package-inventory"; ditto "$work/registry-dump" "$evidence/registry-dump"; cp "$work/report/index.json" "$evidence/automation-index.json"; scan_secrets "$work"; scan_secrets "$evidence"; [[ -z "${P14_WORKSPACE:-}" ]] || scan_secrets "$P14_WORKSPACE"
printf 'phase=P1.4\ntarget=UE %s changelist %s host=%s\ncatalogCount=%s\ncatalogHash=%s\npluginArchitectures=%s\nartifactSha256=%s\npluginSourceTreeSha256=%s\nsourceInventorySha256=%s\nsourceInventoryAfterSha256=%s\ncliSha256=%s\nautomation=33/33-passed\noperationCells=15/15-certified\nblueprintOnlyCookPackage=passed\niostoreAssetRegistry=passed\ntokenScan=passed\n' "$(jq -r .engine.version "$manifest")" "$(jq -r .engine.changelist "$manifest")" "$(uname -m)" "$catalog_count" "$catalog_hash" "$arches" "$artifact" "$plugin_source" "$source_before" "$source_after" "$cli_hash"|tee "$evidence/summary.txt"; printf '%s\n' "$evidence">"$cache_root/latest"; echo "P1.4 native certification: PASS (evidence retained at $evidence)"
