#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)
manifest="$repo_root/tests/unreal/p1.5-manifest.json"
engine_root=$(cd "${UE_ENGINE_ROOT:-/Users/Shared/Epic Games/UE_5.8}" && pwd -P)
editor="$engine_root/Engine/Binaries/Mac/UnrealEditor.app/Contents/MacOS/UnrealEditor"
run_uat="$engine_root/Engine/Build/BatchFiles/RunUAT.sh"
[[ -f "$manifest" && -x "$editor" && -x "$run_uat" ]]
account_home=${P15_ACCOUNT_HOME:-$HOME}
export DOTNET_ROOT="$engine_root/Engine/Binaries/ThirdParty/DotNet/10.0/mac-arm64"
export PATH="$DOTNET_ROOT:$PATH"

cache_root="$account_home/Library/Caches/magi-unreal-axi/p1.5/live"; mkdir -p "$cache_root"
work=$(mktemp -d "$cache_root/work.XXXXXX")
if [[ -n "${P15_LIVE_EVIDENCE_DIR:-}" ]]; then evidence=$P15_LIVE_EVIDENCE_DIR; [[ ! -e "$evidence" ]]; mkdir -p "$evidence"; else evidence=$(mktemp -d "$cache_root/evidence.XXXXXX"); fi
project_dir="$work/project"; project="$project_dir/MagiUnrealAXIFixture.uproject"
bin=${P15_CLI_PATH:-$work/magi-unreal-axi}; plugin_dir=${P15_PLUGIN_DIR:-$work/plugin}; package_project_dir=${P15_PACKAGE_PROJECT_DIR:-}
pid=; session=; tokens=()

level=$(jq -r .fixture.level "$manifest"); abp_path=$(jq -r .fixture.animationBlueprint "$manifest"); abp="$abp_path.$(basename "$abp_path")"
character_path=$(jq -r .fixture.character "$manifest"); character="$character_path.$(basename "$character_path")"; character_class="${character}_C"
skeleton=$(jq -r .fixture.skeleton "$manifest"); mesh=$(jq -r .fixture.skeletalMesh "$manifest"); idle=$(jq -r .fixture.idle "$manifest"); moving=$(jq -r .fixture.moving "$manifest")
expected_catalog_count=${P15_CATALOG_COUNT:-$(jq -r .catalog.count "$manifest")}
expected_catalog_hash=${P15_CATALOG_HASH:-$(jq -r .catalog.sha256 "$manifest")}

editor_alive(){ kill -0 "$1" 2>/dev/null && [[ $(ps -p "$1" -o stat= 2>/dev/null) != Z* ]]; }
axi(){ "$bin" --project "$project" --engine "$engine_root" --timeout 240 --format json "$@"; }
retry(){ local out=$1; shift; for _ in $(seq 1 600); do if axi "$@" >"$out"; then return 0; fi; [[ $(jq -r '.error.reason=="unsafe_editor_state" and .error.retryable==true' "$out" 2>/dev/null) == true ]] || return 1; sleep .2; done; return 1; }
receipt(){ jq -e '.receipt.state=="completed" and .receipt.verification.matched==true' "$1" >/dev/null; local id; id=$(jq -r .receipt.operationId "$1"); axi operation view "$id" >"$work/operation-$id.json"; jq -e --slurpfile m "$1" '.==$m[0].receipt' "$work/operation-$id.json" >/dev/null; }
mutate(){ local out=$1 op=$2 rev=$3 input=$4; retry "$out" capability execute "$op" --expected-revision "$rev" --input-json "$input"; receipt "$out"; jq -e '.result.changed==true' "$out" >/dev/null; }
noop(){ local out=$1 op=$2 rev=$3 input=$4; retry "$out" capability execute "$op" --expected-revision "$rev" --input-json "$input"; receipt "$out"; jq -e --arg rev "$rev" '.result.changed==false and .result.revision==$rev' "$out" >/dev/null; }
stop_editor(){ [[ -n "$pid" ]] || return 0; local p=$pid s=$session; if editor_alive "$p"; then axi --editor "$p" editor stop >/dev/null 2>&1 || true; fi; for _ in $(seq 1 200); do editor_alive "$p" || break; sleep .1; done; editor_alive "$p" && kill -TERM "$p" 2>/dev/null || true; for _ in $(seq 1 100); do editor_alive "$p" || break; sleep .1; done; editor_alive "$p" && kill -KILL "$p" 2>/dev/null || true; wait "$p" 2>/dev/null || true; for _ in $(seq 1 100); do [[ ! -e "$s/bridge-v1.json" && ! -e "$s/token" ]] && break; sleep .1; done; [[ ! -e "$s/bridge-v1.json" && ! -e "$s/token" ]]; pid=; session=; }
start_editor(){ local label=$1; "$editor" "$project" -unattended -nop4 -nosplash -RenderOffscreen -ResX=640 -ResY=360 -NoSound "-abslog=$work/editor-$label-ue.log" >"$work/editor-$label.log" 2>&1 & pid=$!; session="$runtime_root/$pid"; for _ in $(seq 1 1200); do [[ -f "$session/bridge-v1.json" ]] && break; editor_alive "$pid" || return 1; sleep .1; done; [[ -f "$session/bridge-v1.json" && $(jq -r .projectPath "$session/bridge-v1.json") == "$canonical_project" ]]; tokens+=("$(cat "$session/token")"); for _ in $(seq 1 600); do axi --editor "$pid" editor status >"$work/status-$label.json" 2>/dev/null && [[ $(jq -r .editor.state "$work/status-$label.json") == ready ]] && return 0; sleep .1; done; return 1; }
scan(){ local root=$1 secret status; [[ -z "$(find "$root" -type f \( -name token -o -name bridge-v1.json \) -print -quit)" ]]; set +e; grep -R -I -E -q 'Authorization:[[:space:]]*Bearer[[:space:]]+[A-Za-z0-9._-]+' "$root"; status=$?; set -e; [[ $status == 1 ]]; for secret in "${tokens[@]}"; do set +e; grep -R -I -Fq -- "$secret" "$root"; status=$?; set -e; [[ $status == 1 ]]; done; }
cleanup(){ local status=$?; trap - EXIT; stop_editor || status=1; if [[ $status != 0 ]]; then echo "P1.5 live certification failed; work=$work evidence=$evidence" >&2; exit "$status"; fi; [[ ${KEEP_P15_WORK:-0} == 1 ]] || /usr/bin/trash "$work" 2>/dev/null || true; }; trap cleanup EXIT

copy_tracked_tree() { local source=$1 destination=$2 relative; mkdir -p "$destination"; while IFS= read -r -d '' relative; do relative=${relative#"$source"/}; [[ -f "$repo_root/$source/$relative" && ! -L "$repo_root/$source/$relative" ]] || return 1; mkdir -p "$destination/$(dirname "$relative")"; cp -p "$repo_root/$source/$relative" "$destination/$relative"; done < <(git -C "$repo_root" ls-files -z -- "$source/"); }
mkdir -p "$project_dir/Plugins"; copy_tracked_tree tests/unreal/MagiUnrealAXIFixture "$project_dir"; copy_tracked_tree tests/unreal/MagiP15AnimationSeed/Content "$project_dir/Content"
if [[ -z "${P15_CLI_PATH:-}" ]]; then cargo build --release --locked --manifest-path "$repo_root/Cargo.toml" >"$work/rust-build.log" 2>&1; cp "$repo_root/target/release/magi-unreal-axi" "$bin"; fi
chmod 0755 "$bin"; cli_hash=$(shasum -a 256 "$bin"|cut -d' ' -f1); [[ -z "${P15_CLI_SHA256:-}" || $cli_hash == "$P15_CLI_SHA256" ]]
if [[ -z "${P15_PLUGIN_DIR:-}" ]]; then "$run_uat" BuildPlugin -Plugin="$repo_root/plugin/MagiUnrealAXI/MagiUnrealAXI.uplugin" -Package="$plugin_dir" -TargetPlatforms=Mac >"$work/plugin-build.log" 2>&1; fi
plugin_binary=$(find "$plugin_dir" -type f -name "$(jq -r .plugin.binary "$manifest")" -print -quit); [[ -n "$plugin_binary" ]]; artifact=$(shasum -a 256 "$plugin_binary"|cut -d' ' -f1); [[ -z "${P15_PLUGIN_SHA256:-}" || $artifact == "$P15_PLUGIN_SHA256" ]]
ditto "$plugin_dir" "$project_dir/Plugins/MagiUnrealAXI"; copied_plugin_binary=$(find "$project_dir/Plugins/MagiUnrealAXI" -type f -name "$(jq -r .plugin.binary "$manifest")" -print -quit); [[ -n "$copied_plugin_binary" && $(shasum -a 256 "$copied_plugin_binary" | cut -d' ' -f1) == "$artifact" ]]; "$engine_root/Engine/Build/BatchFiles/Mac/Build.sh" MagiUnrealAXIFixtureEditor Mac Development "$project" -WaitMutex >"$work/fixture-build.log" 2>&1
/usr/bin/trash "$project_dir/Plugins/MagiUnrealAXI/Binaries"
ditto "$plugin_dir/Binaries" "$project_dir/Plugins/MagiUnrealAXI/Binaries"
post_build_plugin=$(find "$project_dir/Plugins/MagiUnrealAXI" -type f -name "$(jq -r .plugin.binary "$manifest")" -print -quit); [[ -n "$post_build_plugin" && $(shasum -a 256 "$post_build_plugin" | cut -d' ' -f1) == "${P15_PLUGIN_SHA256:-$artifact}" ]]
canonical_project=$(cd "$project_dir" && pwd -P)/$(basename "$project"); project_hash=$(printf %s "$canonical_project"|shasum -a 256|cut -d' ' -f1)
runtime_root="$account_home/Library/Caches/magi-unreal-axi/$project_hash"; find "$runtime_root" -mindepth 1 -maxdepth 1 -type d -exec /usr/bin/trash {} + 2>/dev/null || true
catalog_line=$(cargo run --locked --manifest-path "$repo_root/Cargo.toml" --bin xtask -- capabilities check); catalog_hash=$(sed -E 's/.*sha256:([0-9a-f]{64})$/\1/' <<<"$catalog_line"); catalog_count=$(sed -E 's/^capability catalog: ([0-9]+) records.*/\1/' <<<"$catalog_line"); [[ "$catalog_count" == "$expected_catalog_count" && "$catalog_hash" == "$expected_catalog_hash" ]]

start_editor author
retry "$work/level-create.json" level create --path "$level"; receipt "$work/level-create.json"
create_abp=$(jq -cn --arg path "$abp_path" --arg skeleton "$skeleton" '{path:$path,skeletonId:$skeleton}'); retry "$work/abp-create.json" capability execute animation_blueprint.create --input-json "$create_abp"; receipt "$work/abp-create.json"; abp_rev=$(jq -r .result.revision "$work/abp-create.json")
variable=$(jq -cn --arg id "$abp" '{animationBlueprintId:$id,name:"Speed",type:"float",source:"owner_planar_speed"}'); mutate "$work/variable.json" animation.variable_ensure "$abp_rev" "$variable"; abp_rev=$(jq -r .result.revision "$work/variable.json")
machine=$(jq -cn --arg id "$abp" '{animationBlueprintId:$id,name:"locomotion"}'); mutate "$work/machine.json" animation.state_machine_ensure "$abp_rev" "$machine"; abp_rev=$(jq -r .result.revision "$work/machine.json"); machine_id=$(jq -r .result.stateMachineId "$work/machine.json")
state_idle=$(jq -cn --arg id "$abp" --arg machine "$machine_id" --arg sequence "$idle" '{animationBlueprintId:$id,stateMachineId:$machine,name:"idle",sequenceId:$sequence}'); mutate "$work/state-idle.json" animation.state_ensure "$abp_rev" "$state_idle"; abp_rev=$(jq -r .result.revision "$work/state-idle.json"); idle_id=$(jq -r .result.stateId "$work/state-idle.json")
state_moving=$(jq -cn --arg id "$abp" --arg machine "$machine_id" --arg sequence "$moving" '{animationBlueprintId:$id,stateMachineId:$machine,name:"moving",sequenceId:$sequence}'); mutate "$work/state-moving.json" animation.state_ensure "$abp_rev" "$state_moving"; abp_rev=$(jq -r .result.revision "$work/state-moving.json"); moving_id=$(jq -r .result.stateId "$work/state-moving.json")
transition_out=$(jq -cn --arg id "$abp" --arg machine "$machine_id" --arg from "$idle_id" --arg to "$moving_id" '{animationBlueprintId:$id,stateMachineId:$machine,fromStateId:$from,toStateId:$to,expression:"Speed > 10"}'); mutate "$work/transition-out.json" animation.transition_ensure "$abp_rev" "$transition_out"; abp_rev=$(jq -r .result.revision "$work/transition-out.json")
transition_back=$(jq -cn --arg id "$abp" --arg machine "$machine_id" --arg from "$moving_id" --arg to "$idle_id" '{animationBlueprintId:$id,stateMachineId:$machine,fromStateId:$from,toStateId:$to,expression:"Speed <= 10"}'); mutate "$work/transition-back.json" animation.transition_ensure "$abp_rev" "$transition_back"; abp_rev=$(jq -r .result.revision "$work/transition-back.json")
create_character=$(jq -cn --arg path "$character_path" '{path:$path,parentClass:"/Script/Engine.Character"}'); retry "$work/character-create.json" capability execute blueprint.create --input-json "$create_character"; receipt "$work/character-create.json"; character_rev=$(jq -r .result.revision "$work/character-create.json")
configure=$(jq -cn --arg id "$character" --arg mesh "$mesh" --arg abp "$abp" '{characterBlueprintId:$id,skeletalMeshId:$mesh,animationBlueprintId:$abp}'); mutate "$work/character-configure.json" animation.character_configure "$character_rev" "$configure"; character_rev=$(jq -r .result.revision "$work/character-configure.json")
retry "$work/abp-compile.json" blueprint compile "$abp" --expected-revision "$abp_rev"; receipt "$work/abp-compile.json"; abp_rev=$(jq -r .result.revision "$work/abp-compile.json"); retry "$work/character-compile.json" blueprint compile "$character" --expected-revision "$character_rev"; receipt "$work/character-compile.json"; character_rev=$(jq -r .result.revision "$work/character-compile.json")
retry "$work/abp-save.json" asset save "$abp" --expected-revision "$abp_rev"; receipt "$work/abp-save.json"; abp_rev=$(jq -r .result.revision "$work/abp-save.json"); retry "$work/character-save.json" asset save "$character" --expected-revision "$character_rev"; receipt "$work/character-save.json"; character_rev=$(jq -r .result.revision "$work/character-save.json")
retry "$work/character-spawn.json" actor spawn --level "$level" --class "$character_class" --agent-key p15-character --label 'P1.5 Character' --location 0,0,100; receipt "$work/character-spawn.json"; retry "$work/level-save.json" level save --path "$level"; receipt "$work/level-save.json"
axi capability execute animation.graph_view --input-json "$(jq -cn --arg id "$abp" '{animationBlueprintId:$id}')" >"$work/graph-author.json"; axi capability execute animation.character_view --input-json "$(jq -cn --arg id "$character" '{characterBlueprintId:$id}')" >"$work/character-author.json"
stop_editor; start_editor restart; retry "$work/level-open.json" level open --path "$level"; receipt "$work/level-open.json"
axi capability execute animation.graph_view --input-json "$(jq -cn --arg id "$abp" '{animationBlueprintId:$id}')" >"$work/graph-restart.json"; axi capability execute animation.character_view --input-json "$(jq -cn --arg id "$character" '{characterBlueprintId:$id}')" >"$work/character-restart.json"; cmp "$work/graph-author.json" "$work/graph-restart.json"; cmp "$work/character-author.json" "$work/character-restart.json"; jq -e --arg rev "$abp_rev" '.revision==$rev and (.variables|length)==1 and (.stateMachines[0].states|length)==2 and (.stateMachines[0].transitions|length)==2' "$work/graph-restart.json" >/dev/null; jq -e --arg rev "$character_rev" --arg abp "$abp" '.revision==$rev and .animationMode=="AnimationBlueprint" and .animationBlueprintId==$abp' "$work/character-restart.json" >/dev/null
retry "$work/noop-abp-create.json" capability execute animation_blueprint.create --input-json "$create_abp"; receipt "$work/noop-abp-create.json"; jq -e --arg rev "$abp_rev" '.result.changed==false and .result.revision==$rev' "$work/noop-abp-create.json" >/dev/null
noop "$work/noop-variable.json" animation.variable_ensure "$abp_rev" "$variable"; noop "$work/noop-machine.json" animation.state_machine_ensure "$abp_rev" "$machine"; noop "$work/noop-state-idle.json" animation.state_ensure "$abp_rev" "$state_idle"; noop "$work/noop-state-moving.json" animation.state_ensure "$abp_rev" "$state_moving"; noop "$work/noop-transition-out.json" animation.transition_ensure "$abp_rev" "$transition_out"; noop "$work/noop-transition-back.json" animation.transition_ensure "$abp_rev" "$transition_back"; noop "$work/noop-character-configure.json" animation.character_configure "$character_rev" "$configure"
stop_editor

if [[ -n "$package_project_dir" ]]; then [[ -f "$package_project_dir/MagiUnrealAXIPackageFixture.uproject" ]]; mkdir -p "$package_project_dir/Content"; for root in MagiP15 MagiP15Seed; do [[ ! -e "$package_project_dir/Content/$root" ]]; ditto "$project_dir/Content/$root" "$package_project_dir/Content/$root"; (cd "$project_dir/Content/$root" && find . -type f -print|LC_ALL=C sort|while read -r f; do printf '%s  %s\n' "$(shasum -a 256 "$f"|cut -d' ' -f1)" "$f"; done) >"$work/source-$root.txt"; (cd "$package_project_dir/Content/$root" && find . -type f -print|LC_ALL=C sort|while read -r f; do printf '%s  %s\n' "$(shasum -a 256 "$f"|cut -d' ' -f1)" "$f"; done) >"$work/destination-$root.txt"; diff -u "$work/source-$root.txt" "$work/destination-$root.txt"; done; package_claim=Content/MagiP15+Content/MagiP15Seed; else package_claim=not-requested; fi
cp "$work"/*.json "$work"/source-*.txt "$work"/destination-*.txt "$evidence/" 2>/dev/null || true; scan "$work"; scan "$evidence"; [[ -z "${P15_WORKSPACE:-}" ]] || scan "$P15_WORKSPACE"
printf 'phase=P1.5\ncatalogHash=%s\nartifactSha256=%s\ncliSha256=%s\nfixture=animation-state-loop\nauthoring=typed-public-cli\nrestart=exact-graph-character-oracles\nnoops=8/8-preserved-revisions\npackage=%s\ntokenScan=passed\n' "$catalog_hash" "$artifact" "$cli_hash" "$package_claim" | tee "$evidence/summary.txt"
[[ -z "${P15_LIVE_EVIDENCE_DIR:-}" ]] && printf '%s\n' "$evidence" >"$cache_root/latest"
echo "P1.5 live certification: PASS (evidence retained at $evidence)"
