#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)
manifest="$repo_root/tests/unreal/p1.5-manifest.json"; p14_manifest="$repo_root/tests/unreal/p1.4-manifest.json"
engine_root=$(cd "${UE_ENGINE_ROOT:-/Users/Shared/Epic Games/UE_5.8}" && pwd -P)
run_uat="$engine_root/Engine/Build/BatchFiles/RunUAT.sh"; editor_cmd="$engine_root/Engine/Binaries/Mac/UnrealEditor-Cmd"; dotnet_root="$engine_root/Engine/Binaries/ThirdParty/DotNet/10.0/mac-arm64"; version_file="$engine_root/Engine/Binaries/Mac/UnrealEditor.version"
[[ -f "$manifest" && -f "$p14_manifest" && -x "$run_uat" && -x "$editor_cmd" && -x "$dotnet_root/dotnet" ]]
operations=(animation_blueprint.create animation.character_configure animation.character_view animation.graph_view animation.state_ensure animation.state_machine_ensure animation.transition_ensure animation.variable_ensure play.animation_observe)
ops_json=$(printf '%s\n' "${operations[@]}"|jq -Rsc 'split("\n")[:-1]')
jq -e --argjson ops "$ops_json" --arg cell '5.8.1-macos-arm64-56057345' --slurpfile p14 "$p14_manifest" '
  .phase=="P1.5" and .engine=={version:"5.8.1",changelist:56057345,hostArchitecture:"arm64"} and .catalog=={count:79,sha256:"a1f1906449ba158584f4b07f0adc0cccb4dba27df12f371e04aadb88452aae8f"} and
  . as $manifest | .seed.glbSha256=="e5127ab92df4d7414e8a78191513b9b6ad1cde3ef699fb2a2a7f04e035f3f286" and (.nativeTests|length)==5 and (.p14RegressionTests|length)==33 and .p14RegressionTests==$p14[0].automationTests and (.automationTests|length)==38 and ((.p14RegressionTests+.nativeTests)|sort)==(.automationTests|sort) and (.automationTests|unique|length)==38 and .knownRegressionWarnings==[{test:"MagiUnrealAXI.P14.AiObserveContracts",warnings:3},{test:"MagiUnrealAXI.P14.BehaviorTreeContracts",warnings:2},{test:"MagiUnrealAXI.P14.BlackboardContracts",warnings:1},{test:"MagiUnrealAXI.P14.NavigationBuildContracts",warnings:3},{test:"MagiUnrealAXI.Read.CatalogContract",warnings:1}] and ([.knownRegressionWarnings[].warnings]|add)==10 and all(.knownRegressionWarnings[];.test as $test|.warnings>0 and ($manifest.p14RegressionTests|index($test))!=null) and
  .pipeline=={blueprintOnly:true,compileAllBlueprints:true,cook:true,package:true} and .plugin.requiredArchitectures==["arm64","x86_64"] and (.packageAssertions.seedFiles|length)==6 and (.packageAssertions.seedObjects|length)==6 and
  (.operationCertificationCells|length)==9 and ([.operationCertificationCells[].operation]|sort)==($ops|sort) and all(.operationCertificationCells[];.cell==$cell)
' "$manifest" >/dev/null
jq -e --argjson ops "$ops_json" --arg cell '5.8.1-macos-arm64-56057345' '[.[]|select(.id as $id|$ops|index($id))]|length==9 and all(.[];.engineSupport.certified==[$cell])' "$repo_root/capabilities/catalog.json" >/dev/null
[[ $(uname -m) == arm64 && $(plutil -extract Changelist raw -o - "$version_file") == 56057345 && "$(plutil -extract MajorVersion raw -o - "$version_file").$(plutil -extract MinorVersion raw -o - "$version_file").$(plutil -extract PatchVersion raw -o - "$version_file")" == 5.8.1 ]]

cache_root="$HOME/Library/Caches/magi-unreal-axi/p1.5/native"; mkdir -p "$cache_root"; work=$(mktemp -d "$cache_root/work.XXXXXX"); evidence=$(mktemp -d "$cache_root/evidence.XXXXXX")
cleanup(){ local status=$?; trap - EXIT; if [[ $status != 0 ]]; then echo "P1.5 certification failed; work=$work evidence=$evidence" >&2; for f in "$work"/*.log "$work"/*.stdout; do [[ -f "$f" ]]&&{ echo "--- $f" >&2; tail -80 "$f" >&2; }; done; exit "$status"; fi; [[ ${KEEP_P15_WORK:-0} == 1 ]]||/usr/bin/trash "$work" 2>/dev/null||true; }; trap cleanup EXIT
source_inventory(){ local out=$1 root; { for root in Cargo.toml Cargo.lock; do [[ -f "$repo_root/$root" ]]&&printf '%s\n' "$repo_root/$root"; done; for root in src capabilities plugin tests/unreal protocol guidance docs; do [[ -d "$repo_root/$root" ]]||continue; find "$repo_root/$root" \( -type d \( -name Saved -o -name Binaries -o -name Intermediate -o -name DerivedDataCache \) -prune \) -o -type f -print; done; }|sed "s#^$repo_root/##"|LC_ALL=C sort -u|while read -r f; do printf '%s\t%s\n' "$f" "$(shasum -a 256 "$repo_root/$f"|cut -d' ' -f1)"; done >"$out"; [[ -s "$out" ]]&&LC_ALL=C sort -c "$out"; }
inventory_tree(){ local root=$1 out=$2; [[ -z "$(find "$root" ! -type d ! -type f -print -quit)" ]]; (cd "$root"&&find . -type f -print|LC_ALL=C sort|while read -r f; do printf '%s\t%s\n' "${f#./}" "$(shasum -a 256 "$f"|cut -d' ' -f1)"; done)>"$out"; }
scan(){ local root=$1 status; [[ -z "$(find "$root" -type f \( -name token -o -name bridge-v1.json \) -print -quit)" ]]; set +e; grep -R -I -E -q 'Authorization:[[:space:]]*Bearer[[:space:]]+[A-Za-z0-9._-]+' "$root"; status=$?; set -e; [[ $status == 1 ]]; }
mkdir -p "$work/project/Plugins" "$work/plugin" "$work/report" "$work/cooked" "$work/package" "$work/package-inventory" "$work/registry-dump"; source_inventory "$work/source-before.txt"; source_before=$(shasum -a 256 "$work/source-before.txt"|cut -d' ' -f1); source_root=$(jq -r .plugin.sourceRoot "$manifest"); inventory_tree "$repo_root/$source_root" "$work/plugin-source.txt"; plugin_source=$(shasum -a 256 "$work/plugin-source.txt"|cut -d' ' -f1)
package_project_dir="$work/package-project"; mkdir -p "$package_project_dir/Config"; cp "$repo_root/tests/unreal/MagiUnrealAXIPackageFixture/MagiUnrealAXIPackageFixture.uproject" "$package_project_dir/"
cat >"$package_project_dir/Config/DefaultEngine.ini" <<EOF
[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=$(jq -r .fixture.level "$manifest")
EditorStartupMap=$(jq -r .fixture.level "$manifest")
GlobalDefaultGameMode=/Script/Engine.GameModeBase
EOF
cat >"$package_project_dir/Config/DefaultGame.ini" <<EOF
[/Script/UnrealEd.ProjectPackagingSettings]
+MapsToCook=(FilePath="$(jq -r .fixture.level "$manifest")")
+DirectoriesToAlwaysCook=(Path="/Game/MagiP15")
+DirectoriesToAlwaysCook=(Path="/Game/MagiP15Seed")
UsePakFile=True
bUseIoStore=True
bUseZenStore=False
EOF
for x in Source Modules Plugins Binaries Intermediate Saved DDC DerivedDataCache Content; do [[ ! -e "$package_project_dir/$x" ]]; done
export DOTNET_ROOT="$dotnet_root" PATH="$dotnet_root:$PATH"

"$repo_root/tests/unreal/verify-p1.5-seed.sh" >"$work/seed-verification.log" 2>&1
catalog_line=$(cargo run --locked --manifest-path "$repo_root/Cargo.toml" --bin xtask -- capabilities check); printf '%s\n' "$catalog_line">"$work/catalog-check.txt"; catalog_count=$(sed -E 's/^capability catalog: ([0-9]+) records.*/\1/'<<<"$catalog_line"); catalog_hash=$(sed -E 's/.*sha256:([0-9a-f]{64})$/\1/'<<<"$catalog_line"); [[ $catalog_count == 79 && $catalog_hash == "$(jq -r .catalog.sha256 "$manifest")" ]]
cargo test --all-targets --all-features --locked --manifest-path "$repo_root/Cargo.toml">"$work/rust-tests.log" 2>&1; cargo build --release --locked --manifest-path "$repo_root/Cargo.toml">"$work/release-build.log" 2>&1; cargo fmt --manifest-path "$repo_root/Cargo.toml" --all -- --check>"$work/fmt.log" 2>&1; cargo +1.88.0 clippy --locked --all-targets --all-features --manifest-path "$repo_root/Cargo.toml" -- -D warnings>"$work/clippy.log" 2>&1
cli="$repo_root/$(jq -r .cli.binary "$manifest")"; [[ -x "$cli" ]]; cli_hash=$(shasum -a 256 "$cli"|cut -d' ' -f1); cp "$cli" "$work/magi-unreal-axi"; chmod 0755 "$work/magi-unreal-axi"
"$run_uat" BuildPlugin -Plugin="$repo_root/plugin/MagiUnrealAXI/MagiUnrealAXI.uplugin" -Package="$work/plugin" -TargetPlatforms=Mac>"$work/plugin-build.log" 2>&1; plugin_binary=$(find "$work/plugin" -type f -name "$(jq -r .plugin.binary "$manifest")" -print -quit); [[ -n "$plugin_binary" ]]; arches=$(lipo -archs "$plugin_binary"); for arch in $(jq -r '.plugin.requiredArchitectures[]' "$manifest"); do grep -qw "$arch"<<<"$arches"; done; [[ $(wc -w<<<"$arches"|tr -d ' ') == 2 ]]; artifact=$(shasum -a 256 "$plugin_binary"|cut -d' ' -f1)
ditto "$repo_root/tests/unreal/MagiUnrealAXIFixture" "$work/project"; ditto "$repo_root/tests/unreal/MagiP15AnimationSeed/Content" "$work/project/Content"; ditto "$work/plugin" "$work/project/Plugins/MagiUnrealAXI"; project="$work/project/MagiUnrealAXIFixture.uproject"; package_project="$package_project_dir/MagiUnrealAXIPackageFixture.uproject"; axi=("$work/magi-unreal-axi" --project "$project" --engine "$engine_root" --timeout 1800 --format json); package_axi=("$work/magi-unreal-axi" --project "$package_project" --engine "$engine_root" --timeout 7200 --format json)
"${axi[@]}" project build>"$work/project-build.json"; jq -e '.operation.status=="passed" or .operation.status=="up_to_date"' "$work/project-build.json">/dev/null; "$editor_cmd" "$project" -run=CompileAllBlueprints -unattended -nop4 -nosplash -nullrhi -NoSound -log="$work/compile.log">"$work/compile.stdout" 2>&1; grep -E '0 error\(s\), 0 warning\(s\)' "$work/compile.stdout">"$work/compile-proof.txt"
"${axi[@]}" project test list --filter MagiUnrealAXI --limit 100 >"$work/test-list.json"; jq -e --slurpfile m "$manifest" '.count==38 and .total==38 and ([.items[].id]|sort)==($m[0].automationTests|sort)' "$work/test-list.json">/dev/null; "${axi[@]}" project test run --filter MagiUnrealAXI --report "$work/report">"$work/test-run.json"; jq -e '.totals.matched==38 and (.totals.succeeded+.totals.succeededWithWarnings)==38 and .totals.failed==0 and .totals.notRun==0 and .totals.inProcess==0 and .totals.errors==0 and .totals.complete==true' "$work/test-run.json">/dev/null; jq -e --slurpfile m "$manifest" --slurpfile manifest "$manifest" '(.tests|map(.fullTestPath)|sort)==($m[0].automationTests|sort) and all(.tests[];(.state=="Success" or .state=="SuccessWithWarnings") and .errors==0) and ([.tests[] as $test|select(($manifest[0].nativeTests|index($test.fullTestPath))!=null and $test.state=="Success" and $test.warnings==0 and $test.errors==0)]|length)==5 and ([.tests[]|select(.warnings>0)|{test:.fullTestPath,warnings}]|sort_by(.test))==($manifest[0].knownRegressionWarnings|sort_by(.test))' "$work/report/index.json">/dev/null
regression_warnings=$(jq -r .totals.warnings "$work/test-run.json"); known_warning_total=$(jq '[.knownRegressionWarnings[].warnings]|add' "$manifest"); [[ $regression_warnings == "$known_warning_total" ]]; jq -e --slurpfile m "$manifest" '(.tests|map({test:.id,warnings})|sort_by(.test))==($m[0].knownRegressionWarnings|sort_by(.test)) and .totals.warnings==([$m[0].knownRegressionWarnings[].warnings]|add)' "$work/test-run.json">/dev/null
live="$work/live-evidence"; P15_LIVE_EVIDENCE_DIR="$live" P15_PACKAGE_PROJECT_DIR="$package_project_dir" P15_CLI_PATH="$work/magi-unreal-axi" P15_CLI_SHA256="$cli_hash" P15_PLUGIN_DIR="$work/plugin" P15_PLUGIN_SHA256="$artifact" P15_WORKSPACE="$work" "$repo_root/tests/unreal/certify-p1.5-live.sh">"$work/live.log" 2>&1; grep -qx 'phase=P1.5' "$live/summary.txt"; grep -qx 'noops=8/8-preserved-revisions' "$live/summary.txt"; grep -qx 'tokenScan=passed' "$live/summary.txt"
for required in "$(jq -r .packageAssertions.animationBlueprint.file "$manifest")" "$(jq -r .packageAssertions.character.file "$manifest")" "$(jq -r .packageAssertions.map.file "$manifest")"; do [[ -f "$package_project_dir/Content/$required" ]]; done; while read -r required; do [[ -f "$package_project_dir/Content/$required" ]]; done < <(jq -r '.packageAssertions.seedFiles[]' "$manifest"); for x in Source Modules Plugins Binaries Intermediate Saved DDC DerivedDataCache; do [[ ! -e "$package_project_dir/$x" ]]; done
"$editor_cmd" "$package_project" -run=CompileAllBlueprints -unattended -nop4 -nosplash -nullrhi -NoSound -log="$work/package-compile.log">"$work/package-compile.stdout" 2>&1; grep -E '0 error\(s\), 0 warning\(s\)' "$work/package-compile.stdout">"$work/package-compile-proof.txt"
"${package_axi[@]}" project cook --output "$work/cooked">"$work/cook.json"; "${package_axi[@]}" project package --output "$work/package">"$work/package.json"; jq -e '.operation.status=="passed" and (.artifacts|length)>0' "$work/cook.json" "$work/package.json">/dev/null; for j in "$work/cook.json" "$work/package.json"; do id=$(jq -r .operation.id "$j"); "${package_axi[@]}" operation view "$id">"$work/operation-$id.json"; jq -e --arg id "$id" '.operation.id==$id and .operation.status=="passed"' "$work/operation-$id.json">/dev/null; done
find "$work/package" -type d -name '*.app' -print -quit|grep -q .; utoc=$(find "$work/package" -type f -name 'MagiUnrealAXIPackageFixture-Mac.utoc' -print -quit); [[ -n "$utoc" ]]; unreal_pak="$engine_root/Engine/Binaries/Mac/UnrealPak"; "$unreal_pak" -ListContainer="$utoc" -Csv="$work/package-inventory/iostore.csv">"$work/package-inventory/unrealpak.log" 2>&1
assert_export(){ awk -F',' -v e="/Content/$1" 'NR>1{f=$5;c=$12;gsub(/^[[:space:]]+|[[:space:]]+$/,"",f);gsub(/^[[:space:]]+|[[:space:]]+$/,"",c);if(substr(f,length(f)-length(e)+1)==e&&c=="ExportBundleData")ok=1}END{exit !ok}' "$work/package-inventory/iostore.csv"; }; assert_export "$(jq -r .packageAssertions.animationBlueprint.file "$manifest")"; assert_export "$(jq -r .packageAssertions.character.file "$manifest")"; assert_export "$(jq -r .packageAssertions.map.file "$manifest")"; while read -r f; do assert_export "$f"; done < <(jq -r '.packageAssertions.seedFiles[]' "$manifest")
registry=$(find "$work/cooked" -type f -name AssetRegistry.bin -print -quit); [[ -n "$registry" ]]; "$editor_cmd" "$package_project" -run=AssetRegistryDump "-input=$registry" "-outdir=$work/registry-dump" -unattended -nop4 -nosplash -nullrhi -NoSound>"$work/registry-dump.log" 2>&1; :>"$work/registry.txt"; while read -r f; do bom=$(od -An -tx1 -N2 "$f"|tr -d '[:space:]'); [[ $bom == fffe || $bom == feff ]]&&iconv -f UTF-16 -t UTF-8 "$f">>"$work/registry.txt"||cat "$f">>"$work/registry.txt"; done < <(find "$work/registry-dump" -type f|LC_ALL=C sort); tr '[:upper:]' '[:lower:]'<"$work/registry.txt">"$work/registry-lower.txt"
group(){ awk -v s="$1" -v e="$2" '$0=="--- begin "s" ---"{i=1;next}i&&/^--- end /{exit f?0:1}i{gsub(/^[[:space:]]+|[[:space:]]+$/,"");if($0==e)f=1}END{exit f?0:1}' "$work/registry-lower.txt"; }; prop(){ awk -v p="$1" -v e="$2" '{l=$0;gsub(/^[[:space:]]+/,"",l)}l~"^"p" :"{i=1;next}i&&l~/^[^[:space:]]/&&l~/ :/{exit f?0:1}i{gsub(/[[:space:]]+$/, "",l);if(l==e)f=1}END{exit f?0:1}' "$work/registry-lower.txt"; }; while read -r object; do group cachedassetsbyobjectpath "$object"; done < <(jq -r '.packageAssertions.seedObjects[],.packageAssertions.animationBlueprint.object,.packageAssertions.character.object' "$manifest"|tr '[:upper:]' '[:lower:]'); map_package=$(jq -r .packageAssertions.map.package "$manifest"|tr '[:upper:]' '[:lower:]'); prop /script/engine.world "$map_package.$(basename "$map_package")"; for key in animationBlueprint character; do object=$(jq -r ".packageAssertions.$key.object" "$manifest"|tr '[:upper:]' '[:lower:]'); package=${object%.*}; generated=$(jq -r ".packageAssertions.$key.generatedRuntime" "$manifest"|tr '[:upper:]' '[:lower:]'); prop generatedclass "$object, /script/engine.$([[ $key == animationBlueprint ]] && printf animblueprintgeneratedclass || printf blueprintgeneratedclass)'$package.$generated'"; done; set +e; grep -R -I -i -E -q '/script/(magiunrealaxifixture|magiunrealaxi)' "$work/registry-lower.txt" "$work/package-inventory"; forbidden=$?; set -e; [[ $forbidden == 1 ]]
inventory_tree "$work/cooked" "$work/package-inventory/cooked.txt"; inventory_tree "$work/package" "$work/package-inventory/package.txt"; source_inventory "$work/source-after.txt"; source_after=$(shasum -a 256 "$work/source-after.txt"|cut -d' ' -f1); diff -u "$work/source-before.txt" "$work/source-after.txt">"$work/source.diff"; [[ ! -s "$work/source.diff" && $source_before == "$source_after" ]]
ditto "$live" "$evidence/live"; cp "$manifest" "$evidence/manifest.json"; cp "$repo_root/tests/unreal/p1.5-seed-provenance.json" "$evidence/seed-provenance.json"; cp "$work"/{catalog-check.txt,seed-verification.log,compile-proof.txt,package-compile-proof.txt,source-before.txt,source-after.txt,source.diff,plugin-source.txt,registry.txt,registry-lower.txt,test-list.json,test-run.json,cook.json,package.json} "$evidence/"; ditto "$work/package-inventory" "$evidence/package-inventory"; ditto "$work/registry-dump" "$evidence/registry-dump"; cp "$work/report/index.json" "$evidence/automation-index.json"; scan "$work"; scan "$evidence"
printf 'phase=P1.5\ntarget=UE %s changelist %s host=%s\ncatalogCount=%s\ncatalogHash=%s\npluginArchitectures=%s\nartifactSha256=%s\npluginSourceTreeSha256=%s\nsourceInventorySha256=%s\nsourceInventoryAfterSha256=%s\ncliSha256=%s\nautomation=38/38-passed\np15Automation=5/5-zero-warnings\nregressionWarnings=%s-known\nrealPIE=idle-moving-idle-passed\nliveAuthorRestartNoop=passed\noperationCells=9/9-certified\nblueprintOnlyCookPackage=passed\niostoreAssetRegistryOwnedContent=passed\ntokenScan=passed\n' "$(jq -r .engine.version "$manifest")" "$(jq -r .engine.changelist "$manifest")" "$(uname -m)" "$catalog_count" "$catalog_hash" "$arches" "$artifact" "$plugin_source" "$source_before" "$source_after" "$cli_hash" "$regression_warnings"|tee "$evidence/summary.txt"; printf '%s\n' "$evidence">"$cache_root/latest"; echo "P1.5 native certification: PASS (evidence retained at $evidence)"
